# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Nick Samson
title: System Validation Engineer
email: me@nicksamson.com
website: www.nicksamson.com

# Social links
#twitter_username: facespics
github_username:  nes77
# dribbble_username: jekyll
# facebook_username: jekyl
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: nes77
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  I'm Nick and I work as a System Validation Engineer predominantly focusing on infrastructure and design of testing software
  for the validation of network accelerator technology. I've got experience debugging every level of the stack from individual bits in hardware
  to kernel drivers to web backends.

  I'm a programming polyglot and love language design. I have significant experience with <mark>Java</mark> and the <mark>JVM</mark>,
   <mark>C++</mark>, <mark>C</mark>, and <mark>Python</mark>, as well as experience using <mark>ANTLR</mark> to write DSLs for <mark>embedded application scripting</mark>.

  I'm interested primarily in SETI and SWE roles at any level of the hardware and software stack.

# Projects Section
# projects_title: Projects

# Experience Section
experience_title: Work Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  When I'm not at work or working on personal software projects, I'm usually [writing or playing music](https://soundcloud.com/cp1116-jazz).

  See my LinkedIn (linked at top of page) for information on classes taken.

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
#  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
